const List<String> tags = [
  'AI/ML',
  'Anime',
  'App dev',
  'Art',
  'AR/VR',
  'Astronomy',
  'Blockchain',
  'Coding',
  'Commerce',
  'Competitive programming',
  'Content creation',
  'Crypto',
  'Cyber Security',
  'Dao',
  'English practice',
  'Entreprenuership',
  'Film/TV',
  'Fitness',
  'Freelancing',
  'Full time jobs',
  'Gaming',
  'Graphic Design',
  'Hackathons',
  'History',
  'Internships',
  'JEE/BITSAT/NEET',
  'Jounalism',
  'Law',
  'Marketing',
  'Medical',
  'Memes',
  'Mental health',
  'Metaverse',
  'Music',
  'NFTs',
  'Personal Finance',
  'Philosophy',
  'Photography',
  'Public Speaking',
  'Quizzing',
  'Reading',
  'Side Hustle',
  'Singing',
  'Sports',
  'Startups',
  'Stock Market',
  'Storytelling',
  'Tech News',
  'UI/UX',
  'Video editing',
];
