// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdvhW5UTbihhZqB9QUrXNJG2NhTu-6fW4',
    appId: '1:447577823119:web:d81437c5e5bc3ce1c29dfa',
    messagingSenderId: '447577823119',
    projectId: 'commect-7631c',
    authDomain: 'commect-7631c.firebaseapp.com',
    storageBucket: 'commect-7631c.appspot.com',
    measurementId: 'G-Q97DTXL77X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV4PV62Lud5lcXrXwpbxWBxQuI0ssVH30',
    appId: '1:447577823119:android:eb46abc203aaad2fc29dfa',
    messagingSenderId: '447577823119',
    projectId: 'commect-7631c',
    storageBucket: 'commect-7631c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW9hceoyJ-6P-eK8wUcFtXp7ue85OY-_g',
    appId: '1:447577823119:ios:0903a4af2ab6beb1c29dfa',
    messagingSenderId: '447577823119',
    projectId: 'commect-7631c',
    storageBucket: 'commect-7631c.appspot.com',
    iosClientId: '447577823119-p46j1ianbb72d1r3ttgii5n77jh5ftua.apps.googleusercontent.com',
    iosBundleId: 'com.example.commect',
  );
}
